version: '3'
services:
  ui-service:
    image: docker-ui-exercise
    container_name: docker-ui-exercise
    restart: always
    build: ./ui
    expose:
      - 4200
    ports:
      - 4200:4200
  api-service:
    image: docker-api-exercise
    container_name: docker-api-exercise
    restart: always
    build: ./
    working_dir: /app
    environment:
      - "LANG=en_US.UTF-8"
      - "LANGUAGE=en_US.UTF-8"
    expose:
      - 8080
    ports:
      - 8080:8080
    command: mvn clean spring-boot:run